---
- name: Install the webserver
  hosts: linux
  remote_user: ec2-user
  become: yes

  tasks: 
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: allow ec2-user to configure Apache
    user:
      name: ec2-user
      groups: apache
      append: yes

  - name: Make sure Apache is running
    service:
      name: httpd
      state: started
      enabled: yes