---
- name: Setup docker
  hosts: linux
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Install yum utils
    yum:
      name: yum-utils
      state: latest

  - name: Install python pip
    yum:
      name: python-pip
      state: present

  - name: Install docker-py with pip
    pip:
      name: docker-py
      # executable: /usr/bin/pip3
      state: present

  - name: Populate service facts
    service_facts:

  - debug:
      msg: Docker installed!
    when: "'docker.service' in services"  

  - name: Install Docker Engine
    shell: amazon-linux-extras install docker -y
    when: "'docker.service' not in services"

  - name: Allow ec2-user to operate docker
    user:
      name: ec2-user
      groups: docker
      append: yes

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes