---
- name: setup the api service
  hosts: linux
  remote_user: ec2-user
  become: yes

  tasks:
  - name: pull the api image
    docker_image:
      name: georgemicro/python-fastapi:1.0.0
      source: pull
      state: present
    
  - name: run a api container
    docker_container:
      name: api_container1
      state: started
      ports: 3000:3000
      image: georgemicro/python-fastapi:1.0.0
