---
- name: setup the database
  hosts: linux
  remote_user: ec2-user
  become: yes

  tasks:
  - name: Install mariadb
    yum:
      name: mariadb-server
      state: present

  - name: Ensure mariadb is started and enabled
    service:
      name: mariadb
      state: started
      enabled: yes
