---
- name: inital setup of the app server
  hosts: linux
  remote_user: root
  
  tasks:
  - name: install EPEL
    yum:
      name: epel-release
      state: present

- name: install the webserver
  hosts: linux
  remote_user: root

  tasks: 
  - name: install httpd
    yum:
      name: httpd
      state: latest

  - name: make sure httpd is running
    service:
      name: httpd
      state: started
      enabled: yes
  
- name: setup the database
  hosts: linux
  remote_user: root

  tasks:
  - name: install postgres related packages
    yum:
      name: ['postgresql-10.17', 'postgresql-server-10.17']
      state: present

  - name: Find out if PostgreSQL is initialized
    stat:
        path: "/var/lib/pgsql/data/pg_hba.conf"
    register: postgres_data

  - name: initialize the database if it is not
    shell: "postgresql-setup initdb"
    when: not postgres_data.stat.exists

  - name: make sure postgres is started and enabled
    service:
      name: postgresql
      state: started
      enabled: yes
